edition = "2021"
hard_tabs = false
indent_style = "Block"
max_width = 100
newline_style = "Auto"
tab_spaces = 4
use_small_heuristics = "Default"
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true