[package]
name = "kadena-client"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
publish.workspace = true
version = "0.1.0"

[dependencies]
tokio = { workspace = true, features = ["full"] }
reqwest= { workspace = true, features = ["json", "multipart"] }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
async-trait.workspace = true
url.workspace = true
ed25519-dalek = "2"
hex.workspace = true
base64.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
hyperlane-core = { path = "../../hyperlane-core"}

[dev-dependencies]
more-asserts = "0.3"
